# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /:year/:month/:day/:title/

# Setup
title:            'Fagner Nunes Carvalho'
description: >
    Hello, welcome!<br/>
    I'm a freelance/consultant focusing on .NET, C# and JS.<br/>
    Working from home for <a href="https://twitter.com/amcsgroup1">@AMCSGroup</a> as a .NET Consultant and <a href="https://twitter.com/amcsgroup1">@ModusCreate</a> as a Senior .NET Engineer.
url:              http://fagner.co/
baseurl:          /

author:
  name:           'Fagner Nunes Carvalho'
  url:            https://twitter.com/fagnerncarvalho

paginate:         5

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
  - pygments.rb
  - classifier-reborn

# Custom vars
version:          3.0

github:
  repo:           https://github.com/fagnercarvalho

disqus:           fagnerblog
